use_frameworks!

platform :ios, '9.0'

target 'AABaiduLocationKit_Example' do
  pod 'AABaiduLocationKit', :path => '../'

  target 'AABaiduLocationKit_Tests' do
    inherit! :search_paths

    
  end
end
