use_frameworks!

platform :ios, '11.0'

target 'AABaiduLocationKit_Example' do
  pod 'AABaiduLocationKit', :path => '../'
#  pod 'BMKLocationKit',:git => 'https://github.com/Z-JaDe/BMKLocationKit.git'
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
